export const networkConfig = {
	dev: {
		rootCA: ""
	},
	test: {
		rootCA: `-----BEGIN CERTIFICATE-----
MIIBiDCCAS2gAwIBAgIGAZhi7awAMAsGCWCGSAFlAwQDCjApMScwJQYDVQQDEx5L
ZWV0YSBUZXN0IE5ldHdvcmsgS1lDIFJvb3QgQ0EwHhcNMjUwODAxMDAwMDAwWhcN
MjgwODAxMDAwMDAwWjApMScwJQYDVQQDEx5LZWV0YSBUZXN0IE5ldHdvcmsgS1lD
IFJvb3QgQ0EwNjAQBgcqhkjOPQIBBgUrgQQACgMiAAKK1O9NiYvu2sBYNRPfjOpp
sNSMZ1lOVn+psFdk3Ugq2qNjMGEwDwYDVR0TAQH/BAUwAwEB/zAOBgNVHQ8BAf8E
BAMCAMYwHwYDVR0jBBgwFoAUap82oKFjJ2jhIj2CGABULiX4h3owHQYDVR0OBBYE
FGqfNqChYydo4SI9ghgAVC4l+Id6MAsGCWCGSAFlAwQDCgNIADBFAiEAqnl85S6v
bw8HLO+YXhnwqq6GmnY+7tCcnwYtoyDzYTMCIEw7ALqHJp0kO9AExm5sSoC7rPOd
GlX42GsZQW3AJ7Jc
-----END CERTIFICATE-----`,
	},
	staging: {
		rootCA: `-----BEGIN CERTIFICATE-----
MIIBjTCCATOgAwIBAgIGAZhi7awAMAsGCWCGSAFlAwQDCjAsMSowKAYDVQQDEyFL
ZWV0YSBTdGFnaW5nIE5ldHdvcmsgS1lDIFJvb3QgQ0EwHhcNMjUwODAxMDAwMDAw
WhcNMjgwODAxMDAwMDAwWjAsMSowKAYDVQQDEyFLZWV0YSBTdGFnaW5nIE5ldHdv
cmsgS1lDIFJvb3QgQ0EwNjAQBgcqhkjOPQIBBgUrgQQACgMiAAODTjEd3jx11AhO
THI3mUZGovIFzfjpiP6h5GgJtNBWDaNjMGEwDwYDVR0TAQH/BAUwAwEB/zAOBgNV
HQ8BAf8EBAMCAMYwHwYDVR0jBBgwFoAULhsbRQxrShU492pxJauVfTC2zzwwHQYD
VR0OBBYEFC4bG0UMa0oVOPdqcSWrlX0wts88MAsGCWCGSAFlAwQDCgNHADBEAiBP
JUe3sQpRjC9xrmP+NocWO+tLaWXlm++UG66uGvYdzgIgC0Cw3G5+pETSVMsQZkc5
bS4b8kNEE+Uqot6w9PMAPC4=
-----END CERTIFICATE-----`
	},
	main: {
		rootCA: `-----BEGIN CERTIFICATE-----
MIIBfjCCASOgAwIBAgIGAZoozMXgMAsGCWCGSAFlAwQDCjAkMSIwIAYDVQQDExlL
ZWV0YSBOZXR3b3JrIEtZQyBSb290IENBMB4XDTI1MTAyODAzMTE0MFoXDTM1MTAy
NjAzMTE0MFowJDEiMCAGA1UEAxMZS2VldGEgTmV0d29yayBLWUMgUm9vdCBDQTA2
MBAGByqGSM49AgEGBSuBBAAKAyIAAzo6Tj4jT/M21M03vMhKIqMbEuVjk+Bma+rf
6bsAF+N/o2MwYTAPBgNVHRMBAf8EBTADAQH/MA4GA1UdDwEB/wQEAwIAxjAfBgNV
HSMEGDAWgBQ7CpYos7ZAi2/GtOMMUxQInwaN+jAdBgNVHQ4EFgQUOwqWKLO2QItv
xrTjDFMUCJ8GjfowCwYJYIZIAWUDBAMKA0gAMEUCIQCOj+uq4Bt7Tdxq1Fo8E4qh
6MbuoX0go3r3aM6WrvQg4wIgCvAoCEfCctmbQ2jhtWcGUVxz2OC8fr6zUrpiE8A9
pMM=
-----END CERTIFICATE-----`
	}
}
