export type IconSize = 16 | 20 | 24 | 32 | 48;

// To get the list of all icon types, run this bash command:
// ls -1 ./src/components/core/Icon/files | sed -e 's/\.svg$//'
export type IconType =
	| 'block'
	| 'building-bank-filled'
	| 'building-bank'
	| 'check'
	| 'chevron-right'
	| 'chevron-up'
	| 'copy'
	| 'eye-off'
	| 'eye'
	| 'filter'
	| 'kebab-menu-horizontal'
	| 'kebab-menu'
	| 'lock'
	| 'menu'
	| 'pencil'
	| 'plus'
	| 'question-mark'
	| 'rotate'
	| 'search'
	| 'social-discord'
	| 'social-x'
	| 'statement-filled'
	| 'statement'
	| 'stats'
	| 'tabler-icon-stack-filled'
	| 'tabler-icon-stack'
	| 'token'
	| 'trash'
	| 'unlock'
	| 'user'
	| 'users-filled'
	| 'users'
	| 'x';
